Terraform 2
Otus-DevOps-2020-11/evsamsonov_infra pull request #8
Opened 2021-03-08 13:42 UTC by evsamsonov

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Удалены результаты выполнения предыдущего ДЗ со звездочкой
- База данных и приложения вынесены на отдельные инстансы
- Конфигурация разделена по файлам
- Добавлены отдельные модули для DB и приложения
- Созданы окружения для stage и prod

## Как запустить проект:

## Как проверить работоспособность:

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2021-03-08 14:34 UTC, evsamsonov commented
Не пойму, что должно быть в storage-bucket.tf
```
  ✔  File terraform/storage-bucket.tf should exist
     ×  File terraform/storage-bucket.tf content should match /\n\Z/
```

В методичке по ДЗ нет упоминания этого файла

2021-03-09 06:34 UTC, mrgreyves requested changes
Здравствуйте!) В storage-bucket.tf должен быть указан конфиг подключения к s3 хранилищу для хранения стейта. Для начала создайте его с фейковыми параметрами.

2021-03-09 17:20 UTC, evsamsonov commented
> Здравствуйте!) В storage-bucket.tf должен быть указан конфиг подключения к s3 хранилищу для хранения стейта. Для начала создайте его с фейковыми параметрами.

Добавил, проверки прошли

2021-03-10 14:17 UTC, evsamsonov commented
@mrgreyves Заапрувите?

2021-03-11 07:28 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-03-11 18:52 UTC, merged